import test from 'node:test';
import assert from 'node:assert/strict';
import { qcFrameCount, validateVisualQuality, evaluateQualitySkill } from '../packages/skills/quality';
import type { Variant } from '../packages/shared/types';

function result(){return {dimensions:{motion_naturalness:22,human_feeling:22,product_fidelity:22,camera_execution:22},evidence:['motion_naturalness','human_feeling','product_fidelity','camera_execution'].map(dimension=>({dimension,description:'Visible frame comparison',status:'observed',severity:'none',confidence:'high',frame_ids:['qc_frame_01'],reference_ids:dimension==='product_fidelity'?['product_01']:[]})),recommendations:[]};}
const validate=(value:unknown)=>validateVisualQuality(value,new Set(['qc_frame_01']),new Set(['product_01']),'V1',0);
test('QC frames bounded to 16 / 24',()=>{assert.equal(qcFrameCount(10),16);assert.equal(qcFrameCount(10.1),24);assert.equal(qcFrameCount(120),24);});
test('QC server computes score, pass and retry',()=>{const report=validate(result());assert.equal(report.overall_score,88);assert.equal(report.passed,true);assert.equal(report.retry_required,false);assert.equal(report.evaluation_mode,'visual');const bad=result();bad.evidence[0].severity='high';const failure=validate(bad);assert.equal(failure.passed,false);assert.equal(failure.retry_required,true);});
test('QC rejects fabricated image evidence and model computed pass',()=>{const bad=result();bad.evidence[0].frame_ids=['qc_frame_99'];assert.throws(()=>validate(bad),/unknown image/);assert.throws(()=>validate({...result(),passed:true}));});
test('QC uncertain cannot prove a defect or trigger paid retry',()=>{const uncertain=result();Object.assign(uncertain.evidence[0],{status:'uncertain',severity:'none',confidence:'low',frame_ids:[]});const report=validate(uncertain);assert.equal(report.passed,false);assert.equal(report.retry_required,false);uncertain.evidence[0].severity='high';assert.throws(()=>validate(uncertain));});
test('non-critical uncertain detail can coexist with observed evidence for its dimension',()=>{const value=result();value.evidence.push({dimension:'motion_naturalness',description:'A small hand detail is uncertain',status:'uncertain',severity:'none',confidence:'low',frame_ids:[],reference_ids:[]});const report=validate(value);assert.equal(report.passed,true);assert.equal(report.retry_required,false);});
test('QC requires reference image for product comparison and evidence for every dimension',()=>{const bad=result();bad.evidence[2].reference_ids=[];assert.throws(()=>validate(bad));const missing=result();missing.evidence[2]=missing.evidence[1];assert.throws(()=>validate(missing),/four dimensions/);});
test('QC live rejects simulations and missing key without fake scoring',async()=>{const variant={id:'V1'} as Variant;await assert.rejects(evaluateQualitySkill('unused',variant,0,{simulatedScore:100}),/forbidden/);await assert.rejects(evaluateQualitySkill('unused',variant,0,{env:{}}),/UNAVAILABLE/);const demo=await evaluateQualitySkill('unused',variant,0,{mode:'mock',simulatedScore:80});assert.equal(demo.evaluation_mode,'mock');});
