import type { Task } from '../shared/types';
// Explicit offline fixture: creative assumptions are not reference observations.
export function mockTreatment(task:Task){
 const unknown='Unknown：Mock 未调用视觉模型，无法根据画面确认';
 const fields=['scene','shot_size','camera_position','camera_angle','camera_motion','composition','subject_trajectory','actions','performance','lighting','rhythm','commercial_intent'];
 const directions=[
  {title:'轻奢时尚',height:'high',camera:'slow forward follow',subject:'short diagonal approach then settle',framing:'medium to detail',entrance:'enters from frame left',ending:'still product presentation',action:'lightly support the product, then reveal its silhouette'},
  {title:'都市通勤',height:'eye-level',camera:'lateral track',subject:'cross frame then pause beside a bench',framing:'wide to medium',entrance:'already moving across the frame',ending:'resume walking past camera',action:'pause to demonstrate everyday use, then continue the journey'},
  {title:'活力街拍',height:'low',camera:'gentle outward arc',subject:'stationary weight shift then quarter turn',framing:'full body to three-quarter',entrance:'product detail foreground reveal',ending:'relaxed off-camera glance',action:'show the side profile, then let the product settle after a small turn'},
 ];
 const performance={gait:'Small steps slow before stopping; no sliding.',body_weight:'Shift weight onto the supporting foot before the turn.',shoulders:'One shoulder follows the head after a short delay.',arms:'Product-holding arm has less swing.',hands:'Support product with relaxed fingers; maintain contact.',gaze:'Notice lens briefly before turning head.',head_movement:'Head follows gaze before shoulders.',facial_expression:'A small smile develops gradually and releases.',breathing:'Quiet breath while settled.',asymmetry:'Unequal arm motion follows the carried load.',clothing_inertia:'Fabric settles after the body.',hair_inertia:'Hair follows head with a slight delay.',props_inertia:'Product follows the hand and settles without jumping.'};
 return {mode:'INSPIRE',reference_analysis:[{reference_id:'reference',...Object.fromEntries(fields.map(f=>[f,unknown])),confidence_notes:[`Observed (ffprobe): ${task.metadata?.duration}s, ${task.metadata?.width}x${task.metadata?.height}.`,'Inferred: none. Unknown: all visual behavior.']}],shot_dna:{visual_purpose:'假设：让商品外形与使用方式清晰可见',emotion:'假设：克制、生活化的推荐感',camera_language:['假设：摄影机与人物保持可读的空间关系'],product_display_logic:['假设：先看到轮廓，再看到使用方式'],keep:['商业表达目的（待真实分析验证）','产品可读性'],mutate:['人物路线','机位高度','运镜路径','动作顺序','开场与结尾']},variations:directions.map((d,i)=>{
 const states=[`${d.entrance}; weight prepared; product supported`,`${d.subject}; gaze briefly notices camera; contact retained`,`${d.ending}; fabric and product settled`];
 const segments=[0,1].map(j=>({segment_id:`s${j+1}`,time_range:`${j*4}-${j*4+4}s`,duration:4,start_state:states[j],end_state:states[j+1],transition:j===0?`${d.action}; gaze leads head, shoulders follow, weight transfers before torso.`:'Decelerate, retain hand contact, let cloth settle and expression soften.',body_weight:performance.body_weight,gaze:performance.gaze,facial_expression:performance.facial_expression,arm_motion:performance.arms,secondary_motion:performance.props_inertia,camera_state:`${d.height}; ${d.camera}; ${d.framing}`,subject_position:d.subject}));
 const prompt=`8-second commercial concept, creative assumption for an offline demo. Use supplied person and product reference images when available. ${d.height} camera, ${d.camera}; ${d.framing}. 0–4s: ${d.entrance}; ${d.subject}; ${d.action}. Gaze precedes head, then shoulders and weight shift. 4–8s: ${d.ending}; keep product visible; holding arm moves less, fabric settles after the body. Small expression changes, restrained conversational presentation. Soft daylight. No unsupported product claims.`;
 return {id:`V${i+1}`,title:d.title,concept:`创意假设：${d.camera} / ${d.subject} / ${d.action}`,changed_dimensions:['camera_height','camera_trajectory','subject_trajectory','framing','entrance','ending'],performance_direction:performance,timeline:{segments,continuity_check:'pass',bridged_discontinuities:[]},similarity_report:{subject_trajectory:'low',camera_trajectory:'low',action_sequence:'medium',framing:'low',timing:'high',composition:'medium',decision:'pass-with-risk',rewrite_note:'Mock: comparison with reference is unverified; values are fixture data, not visual findings.'},compiled_prompts:{seedance:{complete_prompt:prompt,shot_prompt:prompt,motion_prompt:d.subject,performance_prompt:performance.gaze,negative_prompt:'foot sliding, rigid fingers, simultaneous eye-head-body rotation, abrupt pose switching, distorted product',first_frame:states[0],last_frame:states[2],reference_usage:'Images guide product and subject identity; reference video is analyzed only. Actual support depends on configured Seedance model.'}}};
 }),assumptions:['Mock 方案用于验证数据流，不理解上传商品或用户要求；真实个性化需启用 DeepSeek Director。',`用户输入作为原始任务保存：${task.requirement}`],limitations:['未运行视觉模型；参考相似度未验证；Mock 视频只是参考素材的本地转码预览。'],quality_check:{timeline_continuity:'pass',variation_diversity:'pass',similarity_guard:'fail',prompt_completeness:'pass'}};
}
