'use client';
/* eslint-disable @next/next/no-img-element */
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { Aperture,ArrowDownToLine,ArrowRight,Check,ChevronRight,Clapperboard,Clock3,FileText,Film,ImagePlus,Layers3,LoaderCircle,Plus,Sparkles,Upload,X,AlertCircle,ScanLine,SlidersHorizontal } from 'lucide-react';
import type { Task } from '@/packages/shared/types';
const defaultRequirement='参考这个真人视频，为这个产品制作 3 个不同版本的电商广告。人物动作自然，不要机械复刻原视频。保留高级、自然的感觉，但动作、运镜和场景需要有明显差异。人物像真实导购员一样，通过动作、眼神和身体语言自然展示产品版型、材质、设计细节、使用场景与购买理由。';
const names=['轻奢时尚','都市通勤','活力街拍'];
const subtitles=['克制表达，让质感成为主角','走进日常，展现真实使用场景','自然互动，捕捉生活的动感'];
const tags=[['质感','平稳跟随'],['日常','侧向运镜'],['活力','移动机位']];
function localMedia(task:Task,file:string){return `/api/media/${task.id}/${file}`;}
function FilePreview({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return file.type.startsWith('video')?<video src={url} controls preload="metadata"/>:<img src={url} alt={file.name}/>;}
export default function Home(){
 const [reference,setReference]=useState<File|null>(null);const [models,setModels]=useState<File[]>([]);const [products,setProducts]=useState<File[]>([]);const [requirement,setRequirement]=useState(defaultRequirement);
 const [task,setTask]=useState<Task|null>(null);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('');const [pollError,setPollError]=useState('');const [config,setConfig]=useState({provider:'mock',director:'mock',directorLabel:'Mock Director'});const [showPlan,setShowPlan]=useState(false);
 const resultRef=useRef<HTMLElement>(null);
 const busy=submitting||!!task&&!['COMPLETED','FAILED'].includes(task.status);
 const taskId=task?.id;const taskStatus=task?.status;
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(setConfig).catch(()=>setError('无法读取服务配置'));const paramId=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('task'):null;const saved=paramId||localStorage.getItem('director-task');if(saved){fetch('/api/tasks/'+saved).then(async r=>{if(r.ok){setTask(await r.json());if(paramId)localStorage.setItem('director-task',paramId);}else localStorage.removeItem('director-task');}).catch(()=>setPollError('无法恢复任务，请刷新重试'));}else{fetch('/api/tasks').then(r=>r.json()).then(d=>{if(d.latest)fetch('/api/tasks/'+d.latest).then(async r=>{if(r.ok){const t=await r.json();setTask(t);localStorage.setItem('director-task',t.id);}});}).catch(()=>{});}},[]);
 useEffect(()=>{if(!taskId||!taskStatus||['COMPLETED','FAILED'].includes(taskStatus))return;let cancelled=false;const timer=setInterval(async()=>{try{const r=await fetch('/api/tasks/'+taskId);if(!r.ok)throw new Error();const data=await r.json();if(!cancelled){setTask(data);setPollError('');}}catch{if(!cancelled)setPollError('连接暂时中断，正在自动重新连接…');}},1000);return()=>{cancelled=true;clearInterval(timer);};},[taskId,taskStatus]);
 function addImages(files:FileList|null,kind:'model'|'product'){if(!files)return;const items=Array.from(files);if(items.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024)){setError('图片需为 JPG / PNG / WebP，单张不超过 10 MB');return;}if(items.length+models.length+products.length>9){setError('模特和商品图片合计最多 9 张');return;}setError('');if(kind==='model')setModels(v=>[...v,...items]);else setProducts(v=>[...v,...items]);}
 async function start(){setError('');if(!reference){setError('请先上传参考视频');return;}if(!requirement.trim()){setError('请输入创作要求');return;}setSubmitting(true);try{const form=new FormData();form.set('referenceVideo',reference);form.set('requirement',requirement);models.forEach(f=>form.append('modelImages',f));products.forEach(f=>form.append('productImages',f));const r=await fetch('/api/tasks',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);setTask(data);localStorage.setItem('director-task',data.id);}catch(e){setError(e instanceof Error?e.message:'上传失败，请重试');}finally{setSubmitting(false);}}
 const phase=task?(['UPLOADED','ANALYZING_REFERENCE'].includes(task.status)?0:task.status==='EXTRACTING_SHOT_DNA'?1:task.status==='PLANNING_VARIANTS'?2:task.status==='COMPLETED'?4:3):-1;
 const completed=task?.results.filter(r=>r.status==='completed').length||0;
 return <div className="studio">
 <header className="topbar"><Link className="brand" href="/"><span className="brand-icon"><Aperture size={29}/></span><span>AI Video Director<small>COMMERCE VIDEO STUDIO</small></span></Link><div className="top-message">用 AI，让好产品被看见<span>从一个灵感，到三种商业表达</span></div><span className="workspace"><span className="online"/>本地工作空间 <span className="avatar">D</span></span></header>
 <aside className="sidebar"><div className="workspace-label">工作空间 <span>01</span></div><a className="nav-active" href="#create"><Clapperboard size={19}/>视频创作<span className="nav-dot"/></a><button onClick={()=>resultRef.current?.scrollIntoView({behavior:'smooth'})}><Layers3 size={19}/>生成结果<span className="count">{completed}</span></button><div className="side-note"><span className="little-orbit"><Aperture size={26}/></span><h3>一个参考，<br/>不止一种可能。</h3><p>保留有效的镜头语言，<br/>创造属于产品的新表达。</p><div className="small-line"/><span>REFERENCE → REIMAGINE</span></div><footer>AI Video Director <span>v0.2 · DeepSeek</span></footer></aside>
 <main id="create"><div className="breadcrumb">工作空间 <ChevronRight size={13}/> 视频创作</div><div className="page-heading"><div><div className="eyebrow"><span/> YOUR NEXT GREAT PRODUCT STORY</div><h1>创建你的<span>商业视频</span></h1><p>上传参考与素材，让 AI 导演把灵感变成三个不同的创意版本。</p></div><div className="mode-label"><span className="online"/>{config.directorLabel} · {config.provider==='mock'?'Mock Video':'Seedance'}</div></div>
 <div className="input-grid"><section className="input-card"><div className="card-heading"><span className="step-icon"><Film size={21}/></span><div><h2>上传参考视频</h2><p>从喜欢的镜头语言开始</p></div><span className="step-number">01</span></div><div className="card-content">{reference?<div className="reference-preview"><FilePreview file={reference}/><div><strong>{reference.name}</strong><small>{(reference.size/1024/1024).toFixed(1)} MB · 已选择</small><button disabled={busy} onClick={()=>setReference(null)} aria-label="移除参考视频"><X size={15}/></button></div></div>:<label className={`dropzone ${busy?'disabled':''}`}><span className="upload-glyph"><Upload size={25}/></span><strong>点击上传参考视频</strong><span>选择一段你喜欢的真人商业视频</span><small>MP4 / MOV · 1–120 秒 · 最大 100 MB</small><input aria-label="参考视频" type="file" accept="video/mp4,video/quicktime,.mov" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){if(!/\.(mp4|mov)$/i.test(f.name)||f.size>100*1024*1024){setError('请选择不超过 100 MB 的 MP4 / MOV');return;}setReference(f);setError('');}e.target.value='';}}/></label>}</div><div className="card-foot"><span className="tiny-dot"/>提取镜头灵感，重新设计表达</div></section>
 <section className="input-card"><div className="card-heading"><span className="step-icon"><ImagePlus size={21}/></span><div><h2>上传模特 / 商品</h2><p>让创意围绕你的产品展开</p></div><span className="step-number">02</span></div><div className="card-content asset-content"><div className="asset-pickers">{(['model','product'] as const).map(kind=><label className="asset-picker" key={kind}><Plus size={25}/><strong>{kind==='model'?'模特素材':'商品素材'}</strong><small>{kind==='model'?'人物 / 穿搭':'外观 / 细节'}</small><input type="file" aria-label={kind==='model'?'模特图片':'商品图片'} accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{addImages(e.target.files,kind);e.target.value='';}}/></label>)}</div>{models.length+products.length>0?<div className="asset-thumbnails">{[...models.map((f,i)=>({f,i,kind:'model'})),...products.map((f,i)=>({f,i,kind:'product'}))].map(({f,i,kind})=><div key={kind+i}><FilePreview file={f}/><button disabled={busy} aria-label={`移除${f.name}`} onClick={()=>kind==='model'?setModels(v=>v.filter((_,x)=>x!==i)):setProducts(v=>v.filter((_,x)=>x!==i))}><X size={12}/></button><span>{kind==='model'?'模特':'商品'}</span></div>)}</div>:<p className="asset-hint">可选上传，多角度素材有助于表达产品细节。</p>}</div><div className="card-foot"><span className="tiny-dot"/>JPG / PNG / WebP · 合计最多 9 张</div></section>
 <section className="input-card requirements"><div className="card-heading"><span className="step-icon"><FileText size={21}/></span><div><h2>输入创作要求</h2><p>告诉导演，你想表达什么</p></div><span className="step-number">03</span></div><div className="card-content"><textarea aria-label="创作要求" disabled={busy} value={requirement} maxLength={5000} onChange={e=>setRequirement(e.target.value)}/><span className="text-count">{requirement.length} / 5000</span><div className="prompt-chips">{['自然导购感','突出产品细节','避免机械复刻'].map(t=><button key={t} disabled={busy||requirement.length+t.length+1>5000} onClick={()=>setRequirement(v=>v+'\n'+t)}><Plus size={11}/>{t}</button>)}</div></div></section></div>
 <div className="generate-row"><div className="generation-info"><span className="mini-stack"><Layers3 size={21}/></span><div><strong>一次创作，三种可能</strong><span>保留镜头精髓，让动作、运镜和表达各有不同</span></div></div><button className="generate-button" disabled={busy} onClick={start}>{busy?<LoaderCircle size={21} className="spin"/>:<Sparkles size={21}/>} {submitting?'正在上传素材…':busy?'导演正在创作…':'开始生成'} {!busy&&<ArrowRight size={18}/>}</button></div>
 {error&&<div role="alert" className="error-banner"><AlertCircle size={17}/>{error}</div>}
 <section className="agent-panel"><div className="section-heading"><div className="section-title"><span className="agent-symbol"><Sparkles size={21}/></span><div><h2>{task?.status==='COMPLETED'?'创作流程已完成':task?.status==='FAILED'?'任务需要处理':busy?'Agent 工作中…':'你的 AI 导演，已准备就绪'}</h2><p>{task?'每一步进度均来自后端任务状态':'从参考分析到视频输出，让创意有迹可循'}</p></div></div><span className={`status-pill ${busy?'working':''}`}><span/>{busy?'正在处理':task?.status==='COMPLETED'?'已完成':task?.status==='FAILED'?'任务失败':'等待素材'}</span></div><div className="steps">{['分析参考视频','提取 Shot DNA','生成 3 套方案',config.provider==='mock'?'Mock 视频输出':'Seedance 生成'].map((name,i)=><div className={`flow-step ${phase>i?'done':''} ${phase===i&&busy?'current':''}`} key={name}><span className="step-circle">{phase>i?<Check size={18}/>:phase===i&&busy?<LoaderCircle size={18} className="spin"/>:String(i+1).padStart(2,'0')}</span><div><strong>{name}</strong><small>{phase>i?'已完成':phase===i&&busy?'进行中':'等待中'}</small></div>{i<3&&<span className="connector"/>}</div>)}</div><div className="agent-log" aria-live="polite">{task?task.logs.slice(-3).map((log,i)=><div key={log.time+i}><time>{new Date(log.time).toLocaleTimeString('zh-CN',{hour12:false})}</time><span className="log-dot"/><span>{log.message}</span></div>):<div><span className="terminal-prompt">›</span><span>添加参考视频和创作要求，开始你的第一条产品故事。</span></div>}{pollError&&<p className="warning">{pollError}</p>}{task?.error&&<p className="warning">{task.error}</p>}</div>{task?.metadata&&<div className="artifacts"><span>{task.metadata.width} × {task.metadata.height} · {task.metadata.duration.toFixed(1)}s · {task.metadata.fps.toFixed(1)} fps</span><a href={localMedia(task,'reference/contact-sheet.jpg')} target="_blank" rel="noreferrer"><ScanLine size={13}/>查看 16 帧联系表</a>{task.plan&&<button onClick={()=>setShowPlan(v=>!v)}><SlidersHorizontal size={13}/>{showPlan?'收起':'查看'}导演方案</button>}</div>}</section>
 {showPlan&&task?.plan&&<section className="plan-panel"><h2>Shot DNA</h2><div className="dna"><p><b>KEEP · 保留</b>{task.plan.shot_dna.keep.join(' / ')}</p><p><b>MUTATE · 变化</b>{task.plan.shot_dna.mutate.join(' / ')}</p></div>{task.plan.variants.map(v=><details key={v.id}><summary>{v.id} · {v.name}</summary><p>{v.creative_direction}</p>{v.product_showcase.map((s,i)=><p key={i}>{typeof s==='string'?s:`商品展示：${s.feature} · ${s.action} · 镜头关注 ${s.camera_focus}`}</p>)}<p>{v.seedance_prompt}</p></details>)}<a href={localMedia(task,'generation-plan.json')+'?download=1'}>下载 generation-plan.json <ArrowDownToLine size={13}/></a></section>}
 <section className="results-section" ref={resultRef}><div className="section-heading"><div className="section-title"><Layers3 size={19}/><h2>创意结果 <span className="result-counter">{completed} / 3</span></h2></div><span className="result-note">同一个产品，不同的精彩</span></div><div className="result-grid">{names.map((name,i)=>{const result=task?.results.find(r=>r.id===`V${i+1}`);return <article className={`result-card result-${i}`} key={name}><div className="result-visual">{result?.url?<video controls preload="metadata" src={result.url}/>:<div className="empty-visual"><div className="frame-corner tl"/><div className="frame-corner tr"/><div className="frame-corner bl"/><div className="frame-corner br"/><span className="visual-orbit">{result?.status==='generating'?<LoaderCircle size={30} className="spin"/>:<Clapperboard size={29}/>}</span><span>{result?.status==='generating'?'视频正在生成':result?.status==='failed'?'生成失败':'等待创意成片'}</span><small>VERSION 0{i+1}</small></div>}<span className="version-tag">V{i+1}</span>{result?.url&&task?.provider==='mock'&&<span className="mock-tag">MOCK · 转码预览</span>}</div><div className="result-body"><div><h3>{result?.name||name}</h3><span className="result-state">{result?.status==='completed'?'已完成':result?.status==='generating'?'生成中':'待生成'}</span></div><p>{result?.error||subtitles[i]}</p><footer><div>{tags[i].map(t=><span key={t}>{t}</span>)}</div>{result?.url&&<a aria-label={`下载 V${i+1}`} href={result.url.startsWith('/')?result.url+'?download=1':result.url} download target={result.url.startsWith('/')?undefined:'_blank'} rel="noreferrer"><ArrowDownToLine size={15}/>下载</a>}</footer></div></article>;})}</div></section>
 <div className="bottom-note"><Clock3 size={13}/>{config.provider==='mock'?'演示模式：真实预处理 + 离线方案 + 参考片转码预览，不代表 AI 广告成片。':'生成时间取决于模型与队列。视频完成后请及时下载保存。'}<span>DIRECTED BY AI. INSPIRED BY YOU.</span></div>
 </main></div>;
}
