import { createHash } from 'node:crypto';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import path from 'node:path';
const pairs=process.argv.slice(2).map((v,i,a)=>v.startsWith('--')?[v.slice(2),a[i+1]]:null).filter(Boolean) as [string,string][];const args=Object.fromEntries(pairs);
for(const key of ['reference-a','reference-b','model','product'])if(!args[key])throw new Error(`Missing --${key}`);
const base=args.base||'http://127.0.0.1:3000';const requirement=args.requirement||'参考这个视频做3个女装广告，人物动作自然，像真人导购一样展示商品，不要机械复刻。';
async function hash(file:string){return createHash('sha256').update(await readFile(file)).digest('hex');}
function diff(a:unknown,b:unknown){const left=JSON.stringify(a),right=JSON.stringify(b);return {different:left!==right,a:a,b:b};}
async function run(label:string,reference:string){const form=new FormData();form.set('referenceVideo',new File([await readFile(reference)],path.basename(reference),{type:'video/mp4'}));form.append('modelImages',new File([await readFile(args.model)],path.basename(args.model),{type:'image/jpeg'}));form.append('productImages',new File([await readFile(args.product)],path.basename(args.product),{type:'image/jpeg'}));form.set('requirement',requirement);const created=await fetch(`${base}/api/tasks`,{method:'POST',body:form});const task=await created.json() as {id?:string;error?:string};if(!created.ok||!task.id)throw new Error(`${label}: ${task.error||created.status}`);const deadline=Date.now()+10*60_000;for(;;){await new Promise(r=>setTimeout(r,2000));const state=await (await fetch(`${base}/api/tasks/${task.id}`)).json() as {status:string;error?:string;plan?:unknown};if(state.status==='COMPLETED')return {label,task_id:task.id,reference_sha256:await hash(reference),plan:state.plan};if(state.status==='FAILED')throw new Error(`${label}: ${state.error}`);if(Date.now()>deadline)throw new Error(`${label}: timeout`);}}
const a=await run('A',args['reference-a']);const b=await run('B',args['reference-b']);const pick=(x:typeof a)=>{const p=x.plan as {reference_analysis:unknown;shot_dna:unknown;variants:{creative_direction:string;structure:unknown;product_showcase:unknown}[]};return {reference_analysis:p.reference_analysis,shot_dna:p.shot_dna,variants:p.variants.map(v=>({creative_direction:v.creative_direction,structure:v.structure,product_showcase:v.product_showcase}))};};
const sa=pick(a),sb=pick(b);const report={created_at:new Date().toISOString(),reference_a_sha256:a.reference_sha256,reference_b_sha256:b.reference_sha256,same_assets:{model_sha256:await hash(args.model),product_sha256:await hash(args.product),requirement},task_ids:{A:a.task_id,B:b.task_id},reference_analysis_diff:diff(sa.reference_analysis,sb.reference_analysis),shot_dna_diff:diff(sa.shot_dna,sb.shot_dna),variant_structure_diff:diff(sa.variants.map(v=>v.structure),sb.variants.map(v=>v.structure)),product_showcase_diff:diff(sa.variants.map(v=>v.product_showcase),sb.variants.map(v=>v.product_showcase)),seedance_prompt_diff:diff((a.plan as {variants:{seedance_prompt:string}[]}).variants.map(v=>v.seedance_prompt),(b.plan as {variants:{seedance_prompt:string}[]}).variants.map(v=>v.seedance_prompt)),manual_review_required:['动作自然度与过渡','人物路线与运镜差异','Evidence 对应帧准确性','KEEP / MUTATE 是否来自参考','商品展示动作能否实际拍摄','商品事实是否有证据']};const dir=path.resolve('data','ab-tests');await mkdir(dir,{recursive:true});const out=path.join(dir,`${Date.now()}.json`);await writeFile(out,JSON.stringify(report,null,2));console.log(out);
