import { createHash } from 'node:crypto';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import path from 'node:path';
const pairs=process.argv.slice(2).map((v,i,a)=>v.startsWith('--')?[v.slice(2),a[i+1]]:null).filter(Boolean) as [string,string][];const args=Object.fromEntries(pairs);
for(const key of ['reference-a','reference-b','model','product'])if(!args[key])throw new Error(`Missing --${key}`);
const base=args.base||'http://127.0.0.1:3000';const requirement=args.requirement||'参考这个视频做3个女装广告，人物动作自然，像真人导购一样展示商品，不要机械复刻。';
async function hash(file:string){return createHash('sha256').update(await readFile(file)).digest('hex');}
async function run(label:string,reference:string){const form=new FormData();form.set('referenceVideo',new File([await readFile(reference)],path.basename(reference),{type:'video/mp4'}));form.append('modelImages',new File([await readFile(args.model)],path.basename(args.model),{type:'image/jpeg'}));form.append('productImages',new File([await readFile(args.product)],path.basename(args.product),{type:'image/jpeg'}));form.set('requirement',requirement);const created=await fetch(`${base}/api/tasks`,{method:'POST',body:form});const task=await created.json() as {id?:string;error?:string};if(!created.ok||!task.id)throw new Error(`${label}: ${task.error||created.status}`);const deadline=Date.now()+10*60_000;for(;;){await new Promise(r=>setTimeout(r,2000));const state=await (await fetch(`${base}/api/tasks/${task.id}`)).json() as {status:string;error?:string;plan?:unknown};if(state.status==='COMPLETED')return {label,task_id:task.id,reference_sha256:await hash(reference),plan:state.plan};if(state.status==='FAILED')throw new Error(`${label}: ${state.error}`);if(Date.now()>deadline)throw new Error(`${label}: timeout`);}}
const a=await run('A',args['reference-a']);const b=await run('B',args['reference-b']);const pick=(x:typeof a)=>{const p=x.plan as {reference_analysis:unknown;shot_dna:unknown;variants:{creative_direction:string;structure:unknown;product_showcase:unknown}[]};return {reference_analysis:p.reference_analysis,shot_dna:p.shot_dna,variants:p.variants.map(v=>({creative_direction:v.creative_direction,structure:v.structure,product_showcase:v.product_showcase}))};};
const report={created_at:new Date().toISOString(),same_assets:{model_sha256:await hash(args.model),product_sha256:await hash(args.product),requirement},A:{...a,summary:pick(a)},B:{...b,summary:pick(b)},manual_review_required:['动作序列与速度差异','摄影机关系差异','证据帧准确性','Shot DNA 是否落实参考差异','商品事实是否有证据']};const dir=path.resolve('data','ab-tests');await mkdir(dir,{recursive:true});const out=path.join(dir,`${Date.now()}.json`);await writeFile(out,JSON.stringify(report,null,2));console.log(out);
